server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
#      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: uniquone-gateway-service

  cloud:
    gateway:
      routes:
#        #Swagger
#        - id: user-service
#          uri: lb://UNIQUONE-USER-SERVICE
#          predicates:
#            - Path=/users/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/users/(?<segment>.*), /$\{segment}
        #Test oauth2 athication
        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/oauth2/**
          filters:
            - RemoveRequestHeader=Cookie
        #Test auth2
        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/login/**
          filters:
            - RemoveRequestHeader=Cookie
#       auth
        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RemoveRequestHeader=Cookie
#        회원가입.
        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/signup/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        #  회원가입, 로그인 외 애
        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/users/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
        - id: post-service
          uri: lb://UNIQUONE-POST-SERVICE
          predicates:
            - Path=/posts/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/posts/(?<segment>.*), /$\{segment}
        - id: chat-service
          uri: lb://UNIQUONE-CHAT-SERVICE
          predicates:
            - Path=/chat/**
jenkins:
  docker-id: ${DOCKERHUB_ID}
  docker-pw: ${DOCKERHUB_PW}
