server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}

spring:
  application:
    name: uniquone-gateway-service

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://13.125.66.71:3000"
              - "http://www.uniquone.shop"
              - "http://uniquone.shop"
            allowedHeaders:
              - "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE
            allow-credentials: true

      routes:
#        #Swagger
#        - id: user-service
#          uri: lb://UNIQUONE-USER-SERVICE
#          predicates:
#            - Path=/users/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/users/(?<segment>.*), /$\{segment}
        #Test oauth2 athication
        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/oauth2/**
#            - RemoveRequestHeader=Cookie
        #Test auth2
        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/login/**
#          filters:
#            - RemoveRequestHeader=Cookie
#       auth
        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/feignUser/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/feignUser/(?<segment>.*), /$\{segment}

        #  회원가입, 로그인 외 애
        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/users/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
#        회원가입.
        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/signup/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}

        - id: post-service
          uri: lb://UNIQUONE-POST-SERVICE
          predicates:
            - Path=/posts/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/posts/(?<segment>.*), /$\{segment}
        # 리뷰, 거래, 문의, 어드민, 신고, 알림, 오퍼, 환경
        - id: post-service
          uri: lb://UNIQUONE-POST-SERVICE
          predicates:
            - Path=/reviews/**, /trade/**, /qna/**, /admin/**, /report/**, /noti/**, /offer/**, /eco/**
#        콘
        - id: post-service
          uri: lb://UNIQUONE-POST-SERVICE
          predicates:
            - Path=/corns/**
          filters:
            - RemoveRequestHeader=Cookie
        # 공통 정보. (1.토큰 던졌을때 유저 pkId ,유저 CornId)
        - id: post-service
          uri: lb://UNIQUONE-POST-SERVICE
          predicates:
            - Path=/commons/**
          filters:
            - RemoveRequestHeader=Cookie
#        Post Comment
        - id: post-service
          uri: lb://UNIQUONE-POST-SERVICE
          predicates:
            - Path=/comment/**
          filters:
            - RemoveRequestHeader=Cookie
#            - AuthorizationHeaderFilter
        - id: post-service
          uri: lb://UNIQUONE-POST-SERVICE
          predicates:
            - Path=/search/**
          filters:
            - RemoveRequestHeader=Cookie
#            - AuthorizationHeaderFilter
        - id: post-service
          uri: lb://UNIQUONE-POST-SERVICE
          predicates:
            - Path=/unistar/**
          filters:
            - RemoveRequestHeader=Cookie
        #            - AuthorizationHeaderFilter
        - id: chat-service
          uri: lb://UNIQUONE-CHAT-SERVICE
          predicates:
            - Path=/chat/**
jenkins:
  docker-id: ${DOCKERHUB_ID}
  docker-pw: ${DOCKERHUB_PW}
