server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka 

spring:
  application:
    name: uniquone-gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://UNIQUONE-USER-SERVICE
          predicates:
            - Path=/users/**
        - id: post-service
          uri: lb://UNIQUONE-POST-SERVICE
          predicates:
            - Path=/posts/**
        - id: chat-service
          uri: lb://UNIQUONE-CHAT-SERVICE
          predicates:
            - Path=/chat/**
jenkins:
  docker-id: ${DOCKERHUB_ID}
  docker-pw: ${DOCKERHUB_PW}
